/*
 * SFC-IVR
 * SFC-IVR-apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceProvider
 */
public class ServiceProviderTest {
    private final ServiceProvider model = new ServiceProvider();

    /**
     * Model tests for ServiceProvider
     */
    @Test
    public void testServiceProvider() {
        // TODO: test ServiceProvider
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'creationTime'
     */
    @Test
    public void creationTimeTest() {
        // TODO: test creationTime
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'initialPassword'
     */
    @Test
    public void initialPasswordTest() {
        // TODO: test initialPassword
    }

    /**
     * Test the property 'isEmailVerified'
     */
    @Test
    public void isEmailVerifiedTest() {
        // TODO: test isEmailVerified
    }

    /**
     * Test the property 'isLoggedIn'
     */
    @Test
    public void isLoggedInTest() {
        // TODO: test isLoggedIn
    }

    /**
     * Test the property 'modificationTime'
     */
    @Test
    public void modificationTimeTest() {
        // TODO: test modificationTime
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'uniqueId'
     */
    @Test
    public void uniqueIdTest() {
        // TODO: test uniqueId
    }

}
