/*
 * SFC-IVR
 * SFC-IVR-apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OtpControllerApi
 */
@Disabled
public class OtpControllerApiTest {

    private final OtpControllerApi api = new OtpControllerApi();

    /**
     * generateOTPForResetPassword
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateOTPForResetPasswordUsingGETTest() throws ApiException {
        String email = null;
        Response response = api.generateOTPForResetPasswordUsingGET(email);
        // TODO: test validations
    }

    /**
     * generateOTPForSignup
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateOTPForSignupUsingGETTest() throws ApiException {
        String email = null;
        Response response = api.generateOTPForSignupUsingGET(email);
        // TODO: test validations
    }

    /**
     * verifyOTP
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyOTPUsingPOSTTest() throws ApiException {
        String email = null;
        String otp = null;
        Response response = api.verifyOTPUsingPOST(email, otp);
        // TODO: test validations
    }

}
