/*
 * SFC-IVR
 * SFC-IVR-apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Response;
import org.openapitools.client.model.SigninResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserControllerApi
 */
@Disabled
public class UserControllerApiTest {

    private final UserControllerApi api = new UserControllerApi();

    /**
     * editProfile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void editProfileUsingPUTTest() throws ApiException {
        String name = null;
        String spId = null;
        String userId = null;
        Response response = api.editProfileUsingPUT(name, spId, userId);
        // TODO: test validations
    }

    /**
     * signin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void signinUsingPOST2Test() throws ApiException {
        String phoneNumber = null;
        String spId = null;
        SigninResponse response = api.signinUsingPOST2(phoneNumber, spId);
        // TODO: test validations
    }

}
